name: img2code
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

dependencies:
  - pip
  - python=3.12.2
  - bzip2
  - ca-certificates
  - libffi
  - libuuid
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib

  - pip:
      - httpcore
      - httpx
      - numpy
      - openai
      - python-dotenv
      - regex
      - requests
      - six
      - urllib3
